//@flow
export const API_REQUEST: 'API_REQUEST' = 'API_REQUEST';

export const ENTITIES: 'ENTITIES' = 'ENTITIES';
export const ENTITIES_RESOLVE: 'ENTITIES_RESOLVE' = 'ENTITIES_RESOLVE';

export const GET_CARS: 'GET_CARS' = 'GET_CARS';
export const GET_CARS_REUQUEST: 'GET_CARS_REUQUEST' = 'GET_CARS_REUQUEST';
export const GET_CARS_SUCCESS: 'GET_CARS_SUCCESS' = 'GET_CARS_SUCCESS';
export const GET_CARS_ERROR: 'GET_CARS_ERROR' = 'GET_CARS_ERROR';
export const CLEAR_CARS_PAGES: 'CLEAR_CARS_PAGES' = 'CLEAR_CARS_PAGES';