//@flow

export const INIT: 'INIT' = 'INIT';
export const API_REQUEST: 'API_REQUEST' = 'API_REQUEST';

export const ENTITIES: 'ENTITIES' = 'ENTITIES';
export const ENTITIES_RESOLVE: 'ENTITIES_RESOLVE' = 'ENTITIES_RESOLVE';

export const GET_CARS: 'GET_CARS' = 'GET_CARS';
export const GET_CARS_REQUEST: 'GET_CARS_REQUEST' = 'GET_CARS_REQUEST';
export const GET_CARS_SUCCESS: 'GET_CARS_SUCCESS' = 'GET_CARS_SUCCESS';
export const GET_CARS_ERROR: 'GET_CARS_ERROR' = 'GET_CARS_ERROR';
export const CLEAR_CARS_PAGES: 'CLEAR_CARS_PAGES' = 'CLEAR_CARS_PAGES'
export const SET_CARS_FILTER: 'SET_CARS_FILTER' = 'SET_CARS_FILTER';
export const SET_CARS_PAGE: 'SET_CARS_PAGE' = 'SET_CARS_PAGE';

export const GET_COLORS_REQUEST: 'GET_COLORS_REQUEST' = 'GET_COLORS_REQUEST';
export const GET_COLORS_SUCCESS: 'GET_COLORS_SUCCESS' = 'GET_COLORS_SUCCESS';
export const GET_COLORS_ERROR: 'GET_COLORS_ERROR' = 'GET_COLORS_ERROR';

export const GET_MANUFACTURERS_REQUEST: 'GET_MANUFACTURERS_REQUEST' = 'GET_MANUFACTURERS_REQUEST';
export const GET_MANUFACTURERS_SUCCESS: 'GET_MANUFACTURERS_SUCCESS' = 'GET_MANUFACTURERS_SUCCESS';
export const GET_MANUFACTURERS_ERROR: 'GET_MANUFACTURERS_ERROR' = 'GET_MANUFACTURERS_ERROR';

export const GET_CAR: 'GET_CAR' = 'GET_CAR';
export const GET_CAR_REQUEST: 'GET_CAR_REQUEST' = 'GET_CAR_REQUEST';
export const GET_CAR_SUCCESS: 'GET_CAR_SUCCESS' = 'GET_CAR_SUCCESS';
export const GET_CAR_ERROR: 'GET_CAR_ERROR' = 'GET_CAR_ERROR';
